# Generated by Django 4.2.5 on 2023-09-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('GD', 'General Dentist'), ('PD', ' Pediatric Dentist'), ('OD', 'Orthodentist'), ('GS', 'Gum Specialist'), ('RCS', 'Root Canal Specialist'), ('OS', 'Oral Surgeon'), ('PTD', 'Prothodontist')], default='GD', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('package_type', models.CharField(choices=[('A', 'Standard'), ('B', 'Premium'), ('C', 'Delux')], default='A', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['title', 'package_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.branch')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinic.package')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the procedure', max_length=255)),
                ('code', models.CharField(help_text='Procedure code or identifier', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the procedure')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Duration of the procedure in minutes')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost of the procedure', max_digits=10)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_details', models.TextField(default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('dental_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.dentalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='clinic.patient')),
            ],
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.dentist'),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.procedure'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.branch')),
                ('dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.dentist')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
    ]
