# Generated by Django 4.2.5 on 2023-09-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['title', 'package_type', 'price']},
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='patient',
        ),
    ]
