# Generated by Django 4.2.5 on 2023-09-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalrecord',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
