# Generated by Django 4.2.5 on 2023-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_dentalrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalrecord',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
