# Generated by Django 4.2.5 on 2023-09-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_package_options_remove_dentist_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='clinic.patient'),
        ),
    ]
