# Generated by Django 4.2.5 on 2023-09-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateField(),
        ),
    ]
