# Generated by Django 4.2.5 on 2023-09-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_paymentrecord_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='dental_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.dentalrecord'),
        ),
    ]
