# Generated by Django 4.2.5 on 2023-09-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_dentalrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
