# Generated by Django 4.2.5 on 2023-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_patient_balance_paymentrecord_dental_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', help_text='Procedure code or identifier', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of the procedure', max_digits=10),
        ),
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the procedure'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the procedure in minutes'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.CharField(default='', help_text='Name of the procedure', max_length=255),
        ),
    ]
