# Generated by Django 4.2.5 on 2023-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_procedure_code_procedure_cost_procedure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='subjective',
            field=models.TextField(blank=True),
        ),
    ]
