# Generated by Django 4.2.5 on 2023-10-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinic.package'),
        ),
    ]
