# Generated by Django 4.2.5 on 2023-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_procedure_assessment_alter_procedure_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(default='', help_text='Procedure code or identifier', max_length=20, unique=True),
        ),
    ]
