# Generated by Django 4.2.6 on 2023-10-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_patient_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinic/images')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='clinic.patient')),
            ],
        ),
    ]
